apiVersion: v1
kind: Service
metadata:
  name: {{ include "farmpro.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "farmpro.fullname" . }}-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
